//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthyClub.Providers.Web.Account {
    
    
    public partial class Default {
        
        /// <summary>
        /// MenuAccountUC1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HealthyClub.Providers.Web.UserControls.MenuAccountUC MenuAccountUC1;
        
        /// <summary>
        /// ProviderAcountSettingUC1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HealthyClub.Providers.Web.UserControls.ProviderAcoountSettingUC ProviderAcountSettingUC1;
    }
}
