//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthyClub.Administration.EDS.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=IECHSDATA\\SHAREPOINT;Initial Catalog=HealthyClub_Boroondara;User ID=D" +
            "eveloper;Password=Password.123;MultipleActiveResultSets=True;Application Name=En" +
            "tityFramework")]
        public string HealthyClub_BoroondaraConnectionString {
            get {
                return ((string)(this["HealthyClub_BoroondaraConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=182.160.159.178;Initial Catalog=HealthyClub_Boroondara_Dev;User ID=HC" +
            "Member;Password=Just1VIPUser;MultipleActiveResultSets=True;Application Name=Enti" +
            "tyFramework")]
        public string HealthyClub_Boroondara_DevConnectionString {
            get {
                return ((string)(this["HealthyClub_Boroondara_DevConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=182.160.159.178;Initial Catalog=HealthyClub_Boroondara;User ID=HCMemb" +
            "er;Password=Just1VIPUser;MultipleActiveResultSets=True;Application Name=EntityFr" +
            "amework")]
        public string HealthyClub_BoroondaraConnectionString1 {
            get {
                return ((string)(this["HealthyClub_BoroondaraConnectionString1"]));
            }
        }
    }
}
